import {NextResponse} from 'next/server';
import {getApiStaff} from '@/lib/auth';
import {prisma} from '@/lib/prisma';
import {writeAudit} from '@/lib/audit';
import {dbProductToCard} from '@/lib/catalog';

const slugify=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
async function relationId(model:'category'|'brand',name:string){const slug=slugify(name);return model==='category'?(await prisma.category.upsert({where:{slug},update:{name},create:{name,slug}})).id:(await prisma.brand.upsert({where:{slug},update:{name},create:{name,slug}})).id}
export async function GET(){const auth=await getApiStaff('products.view');if(!auth.ok)return NextResponse.json({error:'Accès refusé.'},{status:auth.status});const rows=await prisma.product.findMany({include:{category:true,brand:true,variants:{orderBy:{sortOrder:'asc'}},images:{orderBy:{sortOrder:'asc'}}},orderBy:{updatedAt:'desc'}});return NextResponse.json({products:rows.map(dbProductToCard)});}
export async function POST(req:Request){const auth=await getApiStaff('products.create');if(!auth.ok)return NextResponse.json({error:'Accès refusé.'},{status:auth.status});const b=await req.json().catch(()=>({}));const name=String(b.name||'').trim(),sku=String(b.sku||'').trim().toUpperCase();const price=Number(b.price||0),stock=Math.max(0,Number(b.stock||0));if(!name||!sku||price<=0)return NextResponse.json({error:'Nom, SKU et prix valides requis.'},{status:400});const base=slugify(String(b.slug||name));let slug=base,n=2;while(await prisma.product.findUnique({where:{slug}}))slug=`${base}-${n++}`;const categoryId=await relationId('category',String(b.category||'Autres'));const brandId=await relationId('brand',String(b.brand||'Autre'));try{const p=await prisma.product.create({data:{slug,name,shortName:String(b.shortName||name),description:String(b.description||''),status:b.status==='DRAFT'?'DRAFT':'ACTIVE',kind:String(b.kind||'accessory'),tone:String(b.tone||'light'),isNew:!!b.isNew,featured:!!b.featured,bestseller:!!b.bestseller,categoryId,brandId,specs:Array.isArray(b.specs)?b.specs:[],images:{create:(Array.isArray(b.images)?b.images:[]).filter(Boolean).map((url:string,i:number)=>({url,sortOrder:i}))},variants:{create:(Array.isArray(b.variants)&&b.variants.length?b.variants:[{sku,label:b.variantLabel||'Standard',color:b.color,storage:b.storage,memory:b.memory,price,compareAtPrice:b.compareAtPrice,stock}]).map((v:any,i:number)=>({sku:String(v.sku||'').trim().toUpperCase(),label:String(v.label||'Standard'),color:String(v.color||''),storage:String(v.storage||''),memory:String(v.memory||''),price:Number(v.price||0),compareAtPrice:Number(v.compareAtPrice||0)||null,stockOnHand:Math.max(0,Number(v.stock||0)),stockReserved:0,sortOrder:i,stockMovements:{create:{type:'INITIAL',onHandDelta:Math.max(0,Number(v.stock||0)),reason:'Stock initial',actorId:auth.staff.id}}}))}},include:{category:true,brand:true,variants:true,images:true}});await writeAudit(auth.staff.id,'PRODUCT_CREATED','product',p.id,{name,sku,price,stock});return NextResponse.json({product:dbProductToCard(p)},{status:201});}catch(e:any){if(e?.code==='P2002')return NextResponse.json({error:'Ce SKU existe déjà.'},{status:409});throw e}}
