import Header from '@/components/Header';
import BottomNav from '@/components/BottomNav';
import ProductCard from '@/components/ProductCard';
import HomeCarousel from '@/components/HomeCarousel';
import type {Product} from '@/lib/data';
import {getStoreProducts} from '@/lib/catalog';
import {getPublishedHomeSlides} from '@/lib/home-slides';
import {getHomeContent,HomeSectionData} from '@/lib/home-content';
import Link from 'next/link';

function ProductSection({section,items}:{section:HomeSectionData;items:Product[]}){return <section className="wrap homeSelection"><div className="sectionHead"><div>{section.kicker&&<span className="sectionKicker">{section.kicker}</span>}<h2>{section.title}</h2></div>{section.ctaHref&&<Link href={section.ctaHref}>{section.ctaLabel||'Voir tout'} ›</Link>}</div><div className="grid">{items.slice(0,section.itemLimit||4).map(p=><ProductCard key={p.slug} p={p}/>)}</div></section>}
function NewProductsStrip({section,items}:{section:HomeSectionData;items:Product[]}){return <section className="wrap homeSelection"><div className="sectionHead"><div>{section.kicker&&<span className="sectionKicker">{section.kicker}</span>}<h2>{section.title}</h2></div><Link href={section.ctaHref||'/catalogue'}>{section.ctaLabel||'Voir tout'} ›</Link></div><div className="grid newStrip">{items.slice(0,section.itemLimit||10).map(p=><ProductCard key={p.slug} p={p}/>)}</div></section>}
export const dynamic='force-dynamic';
export default async function Home(){const [slides,content,products]=await Promise.all([getPublishedHomeSlides(),getHomeContent(),getStoreProducts()]);const newProducts=products.filter(p=>p.isNew),promoProducts=products.filter(p=>p.promotion),featured=products.filter(p=>p.featured),bestsellers=products.filter(p=>p.bestseller);const banner=content.banners[0];const render=(section:HomeSectionData)=>{if(!section.active)return null;switch(section.key){case'CAROUSEL':return <HomeCarousel key={section.key} slides={slides}/>;case'CATEGORIES':return <section key={section.key} className="homeCats dynamicHomeCats">{content.categories.slice(0,section.itemLimit||6).map(c=><Link key={c.id} href={c.href} style={{background:c.background}}>{c.imageUrl?<div className="homeCatImage"><img src={c.imageUrl} alt=""/></div>:<div className={`homeCatSymbol ${c.symbol==='MAD'?'wide':''}`}>{c.symbol||'M'}</div>}<b>{c.label}</b></Link>)}</section>;case'NEW_PRODUCTS':return <NewProductsStrip key={section.key} section={section} items={newProducts}/>;case'PROMOTIONS':return <ProductSection key={section.key} section={section} items={promoProducts}/>;case'FEATURED':return <ProductSection key={section.key} section={section} items={featured}/>;case'BESTSELLERS':return <ProductSection key={section.key} section={section} items={bestsellers}/>;case'PROMO_BANNER':return banner?<section key={section.key} className="campaignBanner configurableBanner" style={{background:banner.background,color:banner.textColor}}><div>{banner.eyebrow&&<span>{banner.eyebrow}</span>}<h2>{banner.title}</h2>{banner.body&&<p>{banner.body}</p>}{banner.ctaHref&&<Link href={banner.ctaHref}>{banner.ctaLabel||'Découvrir'}</Link>}</div>{banner.imageUrl?<div className="campaignBannerImage"><img src={banner.imageUrl} alt=""/></div>:banner.badge&&<strong>{banner.badge.split(' ').slice(0,-1).join(' ')}<br/><b>{banner.badge.split(' ').slice(-1)}</b></strong>}</section>:null;case'REASSURANCE':return <section key={section.key} className="feature darkFeature"><div>{section.kicker&&<span className="sectionKicker">{section.kicker}</span>}<h2>{section.title}</h2>{section.subtitle&&<p>{section.subtitle}</p>}{section.ctaHref&&<Link href={section.ctaHref}>{section.ctaLabel||'Découvrir'} ›</Link>}</div><div className="orb">M</div></section>;case'UNIVERSES':return <section key={section.key} className="wrap"><h2>{section.title||'Nos univers.'}</h2><div className="categories"><Link href="/catalogue?category=iPhone">iPhone <span>›</span></Link><Link href="/catalogue?category=Mac">Mac <span>›</span></Link><Link href="/catalogue?category=Audio">Audio <span>›</span></Link><Link href="/catalogue?category=Gaming">Gaming <span>›</span></Link></div></section>;default:return null}};return <><Header/><main>{content.sections.sort((a,b)=>a.sortOrder-b.sortOrder).map(render)}</main><BottomNav/></>}
