'use client';
import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronDown, KeyRound, Mail, MoreVertical, Plus, Search, ShieldCheck, Trash2, UserRound, X } from 'lucide-react';
import { allPermissions, PermissionKey, permissionGroups, roleTemplates } from '@/lib/permissions';
import ConfirmDialog from './ConfirmDialog';
type Employee={id:string;name:string;email:string;phone:string;role:string;roleCode:string;status:'Actif'|'Suspendu';lastSeen:string|null;permissions:PermissionKey[];owner?:boolean;mustChangePassword?:boolean};
const roles=['Responsable boutique','Ventes','Stock','Marketing','Personnalisé'];
const blank={name:'',email:'',phone:'',role:'Ventes',password:'',permissions:roleTemplates['Ventes'] as PermissionKey[]};
export default function AdminEmployees(){
 const [employees,setEmployees]=useState<Employee[]>([]),[query,setQuery]=useState(''),[createOpen,setCreateOpen]=useState(false),[permissionOpen,setPermissionOpen]=useState<Employee|null>(null),[menu,setMenu]=useState<string|null>(null),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[error,setError]=useState(''),[deleteTarget,setDeleteTarget]=useState<Employee|null>(null);
 const load=async()=>{setLoading(true);const r=await fetch('/api/admin/staff',{cache:'no-store'});const d=await r.json();if(r.ok)setEmployees(d.staff||[]);else setError(d.error||'Chargement impossible.');setLoading(false)};useEffect(()=>{load()},[]);
 const visible=useMemo(()=>employees.filter(e=>(e.name+' '+e.email+' '+e.role).toLowerCase().includes(query.toLowerCase())),[employees,query]);
 const setRole=(role:string)=>setForm({...form,role,permissions:role==='Personnalisé'?form.permissions:(roleTemplates[role]||[])});const toggleFormPermission=(key:PermissionKey)=>setForm({...form,role:'Personnalisé',permissions:form.permissions.includes(key)?form.permissions.filter(p=>p!==key):[...form.permissions,key]});
 const api=async(url:string,init:RequestInit)=>{setError('');const r=await fetch(url,{...init,headers:{'content-type':'application/json',...(init.headers||{})}});const d=await r.json();if(!r.ok){setError(d.error||'Action impossible.');throw new Error(d.error)}return d};
 const create=async()=>{try{await api('/api/admin/staff',{method:'POST',body:JSON.stringify(form)});setForm(blank);setCreateOpen(false);await load()}catch{}};
 const toggleStatus=async(e:Employee)=>{try{await api(`/api/admin/staff/${e.id}`,{method:'PATCH',body:JSON.stringify({status:e.status==='Actif'?'Suspendu':'Actif'})});setMenu(null);await load()}catch{}};
 const remove=async()=>{if(!deleteTarget)return;try{await api(`/api/admin/staff/${deleteTarget.id}`,{method:'DELETE'});setMenu(null);setDeleteTarget(null);await load()}catch{}};
 const savePermissions=async()=>{if(!permissionOpen)return;try{await api(`/api/admin/staff/${permissionOpen.id}`,{method:'PATCH',body:JSON.stringify({role:permissionOpen.role,permissions:permissionOpen.permissions})});setPermissionOpen(null);await load()}catch{}};
 const seen=(v:string|null)=>v?new Date(v).toLocaleString('fr-FR'):'Jamais connecté';
 return <>{error&&<div className="adminError">{error}</div>}<div className="staffTopCards"><article><span className="staffIcon"><UserRound/></span><div><small>Employés</small><b>{employees.filter(e=>!e.owner).length}</b></div></article><article><span className="staffIcon"><ShieldCheck/></span><div><small>Comptes actifs</small><b>{employees.filter(e=>e.status==='Actif').length}</b></div></article><article><span className="staffIcon"><KeyRound/></span><div><small>Rôles configurés</small><b>{new Set(employees.map(e=>e.role)).size}</b></div></article></div><div className="staffSecurityNote"><ShieldCheck/><div><b>Contrôle d’accès serveur actif</b><span>Les permissions ne servent pas seulement à masquer l’interface : les routes sensibles les vérifient aussi côté serveur.</span></div></div><div className="adminToolbar"><div className="adminSearch"><Search/><input placeholder="Nom, e-mail ou rôle" value={query} onChange={e=>setQuery(e.target.value)}/></div><button onClick={()=>setCreateOpen(true)}><Plus/> Créer un employé</button></div>
 <div className="adminTable staffTable"><div className="adminRow adminHead"><span>Employé</span><span>Rôle</span><span>Accès</span><span>Dernière activité</span><span>Statut</span><span>Actions</span></div>{loading?<p className="tableLoading">Chargement…</p>:visible.map(employee=><div className="adminRow" key={employee.id}><span className="employeeIdentity"><i>{employee.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</i><span><b>{employee.name}</b><small>{employee.email}</small></span></span><span><b>{employee.role}</b>{employee.owner&&<small className="ownerLabel">Compte principal</small>}{employee.mustChangePassword&&!employee.owner&&<small>Mot de passe temporaire</small>}</span><span><button className="permissionCount" onClick={()=>setPermissionOpen(employee)} disabled={employee.owner}>{employee.owner?'Tous les accès':`${employee.permissions.length} permissions`} <ChevronDown/></button></span><span>{seen(employee.lastSeen)}</span><span><i className={employee.status==='Actif'?'staffActive':'staffSuspended'}>{employee.status}</i></span><span className="staffActions"><button className="moreBtn" onClick={()=>setMenu(menu===employee.id?null:employee.id)} disabled={employee.owner}><MoreVertical/></button>{menu===employee.id&&!employee.owner&&<div className="actionMenu"><button onClick={()=>{setPermissionOpen(employee);setMenu(null)}}><KeyRound/> Permissions</button><button onClick={()=>toggleStatus(employee)}>{employee.status==='Actif'?'Suspendre':'Réactiver'}</button><button className="dangerAction" onClick={()=>{setDeleteTarget(employee);setMenu(null)}}><Trash2/> Supprimer</button></div>}</span></div>)}</div>
 {createOpen&&<div className="adminModalShade"><div className="adminModal staffModal"><button className="modalClose" onClick={()=>setCreateOpen(false)}><X/></button><span className="sectionKicker">ÉQUIPE</span><h2>Créer un employé</h2><p className="modalIntro">Le mot de passe est temporaire : l’employé devra le remplacer à sa première connexion.</p><div className="modalGrid"><label>Nom complet<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex. Awa Koné"/></label><label>Téléphone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+225 ..."/></label></div><label>Adresse e-mail<div className="inputWithIcon"><Mail/><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="employe@madstore2.ci"/></div></label><div className="modalGrid"><label>Rôle<select value={form.role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Mot de passe temporaire<input type="password" minLength={12} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="12 caractères minimum"/></label></div><div className="permissionPreview"><div><b>Permissions du rôle</b><span>{form.permissions.length} autorisations activées</span></div><button onClick={()=>setForm({...form,role:'Personnalisé'})}>Personnaliser</button></div>{form.role==='Personnalisé'&&<PermissionMatrix selected={form.permissions} onToggle={toggleFormPermission}/>}<button className="saveProduct" onClick={create}>Créer le compte employé</button></div></div>}
 {permissionOpen&&<div className="adminModalShade"><div className="adminModal permissionsModal"><button className="modalClose" onClick={()=>setPermissionOpen(null)}><X/></button><span className="sectionKicker">AUTORISATIONS</span><h2>{permissionOpen.name}</h2><p className="modalIntro">{permissionOpen.owner?'Le propriétaire possède toujours tous les droits.':'Choisissez précisément ce que cet employé peut consulter ou modifier.'}</p>{!permissionOpen.owner&&<><div className="permissionRoleBar"><label>Modèle de rôle<select value={roles.includes(permissionOpen.role)?permissionOpen.role:'Personnalisé'} onChange={e=>{const value=e.target.value;setPermissionOpen({...permissionOpen,role:value,permissions:value==='Personnalisé'?permissionOpen.permissions:(roleTemplates[value]||permissionOpen.permissions)})}}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><span>{permissionOpen.permissions.length}/{allPermissions.length} permissions</span></div><PermissionMatrix selected={permissionOpen.permissions} onToggle={key=>setPermissionOpen({...permissionOpen,role:'Personnalisé',permissions:permissionOpen.permissions.includes(key)?permissionOpen.permissions.filter(p=>p!==key):[...permissionOpen.permissions,key]})}/><button className="saveProduct" onClick={savePermissions}><Check/> Enregistrer les permissions</button></>}</div></div>}<ConfirmDialog open={!!deleteTarget} title="Supprimer cet accès ?" description={deleteTarget?`Le compte de ${deleteTarget.name} ne pourra plus accéder à l’administration.`:''} confirmLabel="Supprimer l’accès" danger onClose={()=>setDeleteTarget(null)} onConfirm={remove}/></>}
function PermissionMatrix({selected,onToggle}:{selected:PermissionKey[];onToggle:(key:PermissionKey)=>void}){return <div className="permissionMatrix">{permissionGroups.map(group=><section key={group.label}><div className="permissionGroupTitle"><div><b>{group.label}</b><small>{group.description}</small></div><span>{group.permissions.filter(p=>selected.includes(p.key)).length}/{group.permissions.length}</span></div><div className="permissionItems">{group.permissions.map(permission=><label key={permission.key} className={selected.includes(permission.key)?'permissionOn':''}><span>{permission.label}</span><input type="checkbox" checked={selected.includes(permission.key)} onChange={()=>onToggle(permission.key)}/><i/></label>)}</div></section>)}</div>}
