'use client';
import { FormEvent, useState } from 'react';
import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { useRouter } from 'next/navigation';
export default function AdminLogin(){
  const router=useRouter(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);try{const res=await fetch('/api/admin/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Connexion impossible.');router.replace(data.mustChangePassword?'/admin/changer-mot-de-passe':'/admin');router.refresh();}catch(err:any){setError(err.message)}finally{setLoading(false)}}
  return <main className="adminLoginPage"><section className="adminLoginCard"><img src="/brand/logo-transparent.png" alt="MadStore2"/><span className="loginShield"><ShieldCheck/></span><p className="eyebrow">ESPACE SÉCURISÉ</p><h1>Administration</h1><p>Connectez-vous avec votre accès propriétaire ou employé.</p><form onSubmit={submit}><label>Adresse e-mail<div className="loginInput"><Mail/><input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></div></label><label>Mot de passe<div className="loginInput"><LockKeyhole/><input type={show?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShow(!show)} aria-label="Afficher le mot de passe">{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="loginError">{error}</div>}<button className="loginSubmit" disabled={loading}>{loading?'Connexion…':'Se connecter'}</button></form><small>Les actions sensibles sont enregistrées dans le journal d’activité.</small></section></main>
}
