'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowDown,ArrowUp,Eye,EyeOff,ImagePlus,Loader2,Pencil,Plus,Trash2,X} from 'lucide-react';
import ConfirmDialog from './ConfirmDialog';

type Slide={id:string;internalName:string;eyebrow:string|null;title:string;subtitle:string|null;ctaLabel:string|null;ctaHref:string|null;imageUrl:string|null;mobileImageUrl:string|null;background:string;textColor:string;contentAlign:string;active:boolean;sortOrder:number;autoplayMs:number};
type Draft=Omit<Slide,'id'>;
const blank:Draft={internalName:'',eyebrow:'',title:'',subtitle:'',ctaLabel:'En savoir plus',ctaHref:'/catalogue',imageUrl:'',mobileImageUrl:'',background:'#f2f3f5',textColor:'#0b0d12',contentAlign:'CENTER',active:true,sortOrder:0,autoplayMs:5200};
export default function AdminCarousel(){
 const [slides,setSlides]=useState<Slide[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState<Draft>(blank),[saving,setSaving]=useState(false),[error,setError]=useState(''),[removeId,setRemoveId]=useState<string|null>(null);
 const sorted=useMemo(()=>[...slides].sort((a,b)=>a.sortOrder-b.sortOrder),[slides]);
 const load=async()=>{setLoading(true);const r=await fetch('/api/admin/carousel',{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setSlides(j.slides||[]);else setError(j.error||'Impossible de charger le carrousel.');setLoading(false)};
 useEffect(()=>{load()},[]);
 const create=()=>{setEditing(null);setDraft({...blank,sortOrder:slides.length});setError('');setOpen(true)};
 const edit=(s:Slide)=>{const {id,...rest}=s;setEditing(id);setDraft(rest);setError('');setOpen(true)};
 const save=async()=>{if(!draft.internalName.trim()||!draft.title.trim()){setError('Nom interne et titre requis.');return}setSaving(true);setError('');const r=await fetch(editing?`/api/admin/carousel/${editing}`:'/api/admin/carousel',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const j=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setError(j.error||'Enregistrement impossible.');return}setOpen(false);await load()};
 const patch=async(s:Slide,changes:Partial<Slide>)=>{const next={...s,...changes};setSlides(v=>v.map(x=>x.id===s.id?next:x));const r=await fetch(`/api/admin/carousel/${s.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});if(!r.ok)await load()};
 const move=async(s:Slide,dir:-1|1)=>{const i=sorted.findIndex(x=>x.id===s.id),other=sorted[i+dir];if(!other)return;await Promise.all([patch(s,{sortOrder:other.sortOrder}),patch(other,{sortOrder:s.sortOrder})]);};
 const remove=async()=>{if(!removeId)return;const r=await fetch(`/api/admin/carousel/${removeId}`,{method:'DELETE'});if(r.ok)setSlides(v=>v.filter(x=>x.id!==removeId));setRemoveId(null)};
 const upload=async(file:File,target:'imageUrl'|'mobileImageUrl')=>{setSaving(true);setError('');const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/carousel/upload',{method:'POST',body:fd});const j=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setError(j.error||'Upload impossible.');return}setDraft(d=>({...d,[target]:j.url}))};
 return <><div className="carouselAdminToolbar"><div><b>{slides.length} slide{slides.length>1?'s':''}</b><span>La première slide active s’affiche dès l’ouverture de l’accueil.</span></div><button onClick={create}><Plus/> Ajouter une slide</button></div>
 {loading?<div className="carouselAdminEmpty"><Loader2 className="spin"/> Chargement…</div>:sorted.length===0?<div className="carouselAdminEmpty"><ImagePlus/><h3>Aucune slide enregistrée</h3><p>L’accueil utilise actuellement les visuels de démonstration. Ajoutez votre première slide pour prendre le contrôle du carrousel.</p><button onClick={create}>Créer la première slide</button></div>:<div className="carouselAdminList">{sorted.map((s,i)=><article key={s.id} className={!s.active?'isInactive':''}><div className="carouselAdminThumb" style={{background:s.background}}>{s.imageUrl?<img src={s.imageUrl} alt=""/>:<ImagePlus/>}</div><div className="carouselAdminCopy"><span>{s.eyebrow||'SLIDE ACCUEIL'}</span><h3>{s.internalName}</h3><p>{s.title}</p><small>{s.active?'Visible sur le site':'Masquée'} · {Math.round(s.autoplayMs/100)/10}s</small></div><div className="carouselAdminActions"><button title="Monter" disabled={i===0} onClick={()=>move(s,-1)}><ArrowUp/></button><button title="Descendre" disabled={i===sorted.length-1} onClick={()=>move(s,1)}><ArrowDown/></button><button title={s.active?'Masquer':'Afficher'} onClick={()=>patch(s,{active:!s.active})}>{s.active?<Eye/>:<EyeOff/>}</button><button title="Modifier" onClick={()=>edit(s)}><Pencil/></button><button className="danger" title="Supprimer" onClick={()=>setRemoveId(s.id)}><Trash2/></button></div></article>)}</div>}
 {open&&<div className="adminModalShade"><div className="adminModal carouselEditModal"><button className="modalClose" onClick={()=>setOpen(false)}><X/></button><span className="sectionKicker">CARROUSEL ACCUEIL</span><h2>{editing?'Modifier la slide':'Nouvelle slide'}</h2><p className="modalIntro">Le visuel mobile peut être différent du desktop. Pour un rendu premium, privilégiez des images WebP ou PNG détourées et légères.</p>{error&&<p className="carouselFormError">{error}</p>}<div className="carouselFormGrid"><label>Nom interne<input value={draft.internalName} onChange={e=>setDraft({...draft,internalName:e.target.value})} placeholder="Ex. iPhone Duo"/></label><label>Sur-titre<input value={draft.eyebrow||''} onChange={e=>setDraft({...draft,eyebrow:e.target.value})} placeholder="NOUVEAU"/></label><label className="span2">Titre<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Le titre principal"/></label><label className="span2">Sous-titre<input value={draft.subtitle||''} onChange={e=>setDraft({...draft,subtitle:e.target.value})} placeholder="Une courte phrase facultative"/></label><label>Texte du bouton<input value={draft.ctaLabel||''} onChange={e=>setDraft({...draft,ctaLabel:e.target.value})}/></label><label>Lien du bouton<input value={draft.ctaHref||''} onChange={e=>setDraft({...draft,ctaHref:e.target.value})} placeholder="/catalogue"/></label></div><div className="carouselMediaFields"><ImageField label="Visuel desktop" value={draft.imageUrl||''} onUrl={v=>setDraft({...draft,imageUrl:v})} onFile={f=>upload(f,'imageUrl')}/><ImageField label="Visuel mobile" value={draft.mobileImageUrl||''} onUrl={v=>setDraft({...draft,mobileImageUrl:v})} onFile={f=>upload(f,'mobileImageUrl')}/></div><div className="carouselFormGrid compact"><label>Fond<input type="color" value={draft.background} onChange={e=>setDraft({...draft,background:e.target.value})}/></label><label>Texte<input type="color" value={draft.textColor} onChange={e=>setDraft({...draft,textColor:e.target.value})}/></label><label>Alignement<select value={draft.contentAlign} onChange={e=>setDraft({...draft,contentAlign:e.target.value})}><option value="CENTER">Centré</option><option value="LEFT">À gauche</option></select></label><label>Rotation<select value={draft.autoplayMs} onChange={e=>setDraft({...draft,autoplayMs:Number(e.target.value)})}><option value={4000}>4 secondes</option><option value={5200}>5,2 secondes</option><option value={7000}>7 secondes</option><option value={10000}>10 secondes</option></select></label></div><label className="carouselActiveCheck"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/><span><b>Afficher cette slide</b><small>Vous pouvez préparer une campagne et l’activer plus tard.</small></span></label><button className="saveProduct" disabled={saving} onClick={save}>{saving?'Enregistrement…':'Enregistrer la slide'}</button></div></div>}
 <ConfirmDialog open={!!removeId} title="Supprimer cette slide ?" description="Elle disparaîtra immédiatement du carrousel d’accueil. Cette action est définitive." confirmLabel="Supprimer" danger onClose={()=>setRemoveId(null)} onConfirm={remove}/></>;
}
function ImageField({label,value,onUrl,onFile}:{label:string;value:string;onUrl:(v:string)=>void;onFile:(f:File)=>void}){return <div className="carouselImageField"><div className="carouselImagePreview">{value?<img src={value} alt=""/>:<ImagePlus/>}</div><div><b>{label}</b><small>JPG, PNG ou WebP · max 8 Mo</small><label className="carouselUploadBtn"><ImagePlus/> Choisir une image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f)}}/></label><input className="carouselUrlInput" value={value} onChange={e=>onUrl(e.target.value)} placeholder="ou /chemin/image.webp"/></div></div>}
